- .gitignore
- src/pages/resource.astro
Added the appropriate content to the Cards on the resource page. Kindly consider this pull request and merge it under GSSoC'23 :)
> Improved the content of cards on resource page

- src/components/features.astro
**Updated features.astro file with hover effects on the icons.**
These icons will now scale their size, when hovered over.
Thus, solving issue #13 
Please Accept This Contribution for GSSoC'23.
> Updated features.astro with hover effects on icons

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/Pull_Request_Template.md
Closes: #20 
Created ".github" folder and added new templates under "issue_template" to report bugs and add new features.
Created file under ".github" folder and added new template for PR.
This template which you can see right now is pull request template.
|      Bug Report       |       Feature Addition        |         Pull Request    |
| :-----------------: | :------------------: | :------------------: |
|![bugz](https://github.com/ZeroOctave/resource-gallery/assets/119059108/8b31fd1d-b252-41e6-8028-f8e490f4eae5) |![dde](https://github.com/ZeroOctave/resource-gallery/assets/119059108/b6387d10-8a84-425b-8289-ae516e1f002f)| ![tusg](https://github.com/ZeroOctave/resource-gallery/assets/119059108/77622c22-8460-4a2d-8a5d-4e421d6799d6) |
> [PR for #20]: Created Templates to add new feature, report bugs and pull requests.

- src/pages/blog/JavaScript Top 10 Tips & Tricks.md
Added Blog JavaScript Top 10 tips and tricks, fully written by myself. in simple and understandable language.
Issue No #1 
#GSSOC
> Added Blog (JavaScript Top 10 Tips and Tricks)

- .github/pull_request_template.yml
Closes: #66 
Created a good descriptive Pull Request template in .yml so that new contributors can provide better information about their changes to the reviewer.
N/A
> Created The YAML File

- src/pages/webdev.astro
- This PR Fixes/Closes: #64 
- Added new `React` documentation website as a resource under `webdev` category
|     ADDED LINK       |
| :-----------------: |
| ![image](https://github.com/ZeroOctave/resource-gallery/assets/92252895/99afbd1f-7529-4df6-a009-737dc0258f99) |
> 💡 [ADD]: REACT DOCS RESOURCE FOR WEB-DEV

- src/pages/frameworks.asto
- Closes: #71 
- Added 3 new resources for Frameworks
- It includes `Vue.js`, `Express.Js` & `Vite`
- As per request of @Astrodevil, I have modified the `React` Docs from `Web-dev` category to `Frameworks` category
|||
| :---: | :---: |
| ![](https://github.com/ZeroOctave/resource-gallery/assets/92252895/0403b994-2be0-418c-8f46-d6cedaed8a3b) | ![](https://github.com/ZeroOctave/resource-gallery/assets/92252895/64605fbb-e27f-4b0b-802c-36930186612c) |
| ![](https://github.com/ZeroOctave/resource-gallery/assets/92252895/602be37a-c96a-4d34-89d6-ad890efbf4f4) | ![](https://github.com/ZeroOctave/resource-gallery/assets/92252895/fbbd320b-6bb0-4c41-8d0e-f357d40cb4c3) | 
|||
> [Blog]: Add 3 New Resources for Frameworks 💡

- src/components/hero.astro
- src/layouts/Layout.astro
Closes: #83
Added animation in Hero section (text and image both )
For example:
On reload the page image zoom in and left side text hinge once 
- [x ] My code adheres to the established style guidelines of this project.
- [ x] I have conducted a self-review of my code.
- [x ] My changes have not introduced any new warnings.
##Updated
https://github.com/ZeroOctave/resource-gallery/assets/101205226/4b81d8c9-7b52-445e-86f1-1ab1cf50ebd3
> added animation on hero sec

- src/pages/frameworks.astro
- src/pages/webdev.astro
Closes: #38 
Added two new resource blog and website for react.
> Added in resources - Blog and website

- src/components/navbar/navbar.astro
Closes: #[issue number]
#77 
- [x ] I have conducted a self-review of my code.
- [ x] My changes have not introduced any new warnings.
| ![Original screenshot](link)
| ![Updated screenshot](link)
|
>  #77 add home in the navbar [GSSOC'23]

- src/pages/opensource/programs.md
Closes: #60 
I added two open source program in open source program section of the website.
> adding open source programs 

- package-lock.json
- src/components/navbar/navbar.astro
- tailwind.config.cjs
Previously Z-Index of navbar was low as compared to other contents because of that all other things were going on top of the navbar . 
Closes: #92 
I have increased the Z-Index of navbar so that other things does not go on top of the navbar while scrolling down . 
**Orignal**
https://github.com/ZeroOctave/resource-gallery/assets/85991449/eef5e85f-be8f-42d3-bc27-601ad2b1c9f0
**Updated**
https://github.com/ZeroOctave/resource-gallery/assets/85991449/de0cc021-6f87-4cae-a343-b5a3f836b815
> Fixed : issue #92

- package-lock.json
- src/components/navbar/navbar.astro
For Issue #103 
Closes: #103 
Navbar - Backdrop-filter: blur and Z-index for Navbar added in tailwind "backdrop-blur z-10"
| ![image](https://github.com/ZeroOctave/resource-gallery/assets/113185442/4bb795c1-400e-45bd-a19e-596cb462927f) | ![image](https://github.com/ZeroOctave/resource-gallery/assets/113185442/6857da89-f58f-46f2-95b6-d7f25e60fa45) |
> Issue #103 - PR for Navbar Update

- src/pages/about.astro
Closes: #[issue number]
#100
Improve the UI of the About page
Added some additional properties to the design of the page
| ![Original screenshot]( 
)
| ![Updated screenshot](
) |
> About page UI issue were resolved.

- src/pages/opensource/programs.md
Closes: #110
Added new Open Source resources.
This PR is part of GSSoC'23.
| ![Original screenshot](https://github.com/ZeroOctave/resource-gallery/assets/89148144/dc6ecc7e-5793-4272-aa6b-5b175fc538ce) | ![Updated screenshot](https://github.com/ZeroOctave/resource-gallery/assets/89148144/b887d9d5-22a7-4092-bcf6-f7ad56ea8f18) |
> Add Open Source Programs

- src/pages/about.astro
Reverts ZeroOctave/resource-gallery#115
> Revert "About page UI issue were resolved."

- src/components/footer.astro
- src/components/ui/link.astro
Social handles in the footer section and the "Contribute to Regala" should open on a new page to enhance user experience.
Closes: #165
I have made the required changes to redirect all the social handles in the footer and the "Contribute to Regala" to a new page
> #165 Issue fixed

- src/pages/webdev.astro
Closes: #168 
Added the three resources on next js in web development section. kindly review it.
> added resources

- src/pages/cloud.astro
- src/pages/resource.astro
Closes: #169 
Added new resources for cloud. Created a new section for cloud and added 6 resources under it including blogs, documentation and tutorials for aws, azure and google cloud.
> add new resources

- .github/workflows/codeql.yml
Reverts ZeroOctave/resource-gallery#188
> Revert "Revert "feat: add codeql workflow""

- src/pages/blog.astro
Closes: #182 
-Added a share icon alongside the category of the blog
-Added the functionality of copying the link to the blog 
-Added an alert for confirmation
|      Updated       |  
[Video Preview]
https://www.loom.com/share/69d4b3e485194a848353c3e40b963ab6?sid=db23c2fb-0e8a-442d-8d9f-cc62bf3eec15
> Share functionality added

- src/pages/blog/A-Complete-Guide-to-React-Hooks-Discover-Their-Features.md
Closes: #195 
I have added the blog related to the React Hooks and features.
Please review it and If it is fine then please merge it to the main branch.
> Added the resources about the React Hooks and their features by Parmesh Bhatt

- src/components/footer.astro
- src/components/logos.astro
Closes: #[#152]
-Added color to the social icons
-Added colors on the hover effect 
| ![Original screenshot]( 
) | ![Updated screenshot](
https://github.com/ZeroOctave/resource-gallery/assets/83147410/35b511d6-b1bd-4c0b-8872-715f0f276d47
) |
> Added effecting hover effect on the icons

- src/pages/blog/Understanding Cloud Technology: A Comprehensive Guide.md
- src/pages/blog/src/pages/blog/Low code and no-code tools.md
added one more blog 
Closes: #229
added new blog
> blog added

- package-lock.json
- src/pages/about.astro
- src/pages/blog.astro
solves #211 
https://github.com/ZeroOctave/resource-gallery/assets/94003231/0726bfe5-7f02-4d36-8dd1-ba3364cc2073
Closes: #[issue number]
> Add our team section

- src/pages/blog/will-AI-replace-Humans.md
Closes: #[#231]
Added blog on the Will AI replace the humans
https://github.com/ZeroOctave/resource-gallery/assets/83147410/545ba720-29fb-4cad-834c-3920e1651568
> Added blog on the Will AI Replace Humans

- src/pages/about.astro
- Added my profile details in proper format.
- Tested ✅
> Feat: added Ganesh Mourya as maintainer

- src/pages/webdev.astro
Closes: #190 
- Added NodeJs and MongoDB resources
- Modified only webdev.astro file
> Added NodeJs and MongoDB Resources

- src/pages/frameworks.astro
- src/pages/javascript.astro
- src/pages/webdev.astro
Closes: #240 #241 #239 
- **`Replaced Resource Gallery - Frameworks instead of  changed Resource Gallery - Frameworks/Libraries/Tools` in this https://resourcegallery.live/frameworks/   Link**
- **Added `The Odin Project` Details in `src/pages/webdev.astro` File** 
- **Added `Cisco Networking Academy` Details in `src/pages/javascript.astro` File**
> fix: Modifications in frameworks.astro , webdev.astro, javascript.astro Files

- src/components/features.astro
https://github.com/ZeroOctave/resource-gallery/issues/226
Closes: #226 
I have added hover to the cards
- [ x] My code adheres to the established style guidelines of this project.
- [ x] I have conducted a self-review of my code.
- [ x] I have included comments in areas that may be difficult to understand.
- [ x] I have made corresponding updates to the project documentation.
- [ x] My changes have not introduced any new warnings.
> Added hovers to the cards

- src/pages/frameworks.astro
> #264 new docs Added

- src/pages/webdev.astro
Closes: #260 
- **Added `DevDocs.io` Website Details in `webdev.astro` File for `Learning Multiple Technologies in More clear and Comfortable Manner`**
> feat: DevDocs.io

- src/components/navbar/dropdown.astro
- src/components/navbar/navbar.astro
Closes: #[#232]
-Added Underline effect on hover
-Improve the  UI of the dropdown menu
-[x] My code adheres to the established style guidelines of this project.
> Improve the hover and dropdown menu of the navbar

- src/pages/javascript.astro
> Adding DOM manipulation blog post in javascript resources

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/styles.yml
Closes: #283 
- **Added styles.yml File and config.yml File in GitHub Issue Templates List.**
> fix: Added styles.yml amd config.yml Files in GitHub Issues Templates

- package-lock.json
- pnpm-lock.yaml
- src/pages/css.astro
- src/pages/css/books.md
- src/pages/css/games.md
- src/pages/css/resources.md
- src/pages/cybersecurity/books.md
- src/pages/resource.astro
Closes: #282 
I have added a new section to the resources gallery "CSS" and in that, I have added the books section, resources section, and gaming adventures section.
| (
> chore: CSS Gallery

- src/components/contactform.astro
- src/components/footer.astro
Closes: #273 
- `Added ARIA Attributes to Form Section in contactform.astro File.`
- `Also, Added ARIA Attributes, title(Tooltip), rel Attributes in footer.astro File.`
> fix: Added ARIA Attributes to Form Sections and Social Icons
